sudo: false
language: php
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.composer/cache
notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
  - name: Test with PHP 7.4
  - name: Test with PHP Nightly
  include:

  - name: Test coding style
    php: '7.3'
    before_script:
    - phpenv config-rm xdebug.ini || true
    - composer --no-interaction remove --dev --no-update phpunit/phpunit
    - travis_retry composer --no-interaction install --classmap-authoritative
    script:
    - composer --no-interaction run-script cs-test -- --using-cache=no .

  - name: Test with PHP 5.3
    dist: precise
    php: '5.3'
    before_script:
    - phpenv config-rm xdebug.ini || true
    - composer --no-interaction remove --dev --no-update friendsofphp/php-cs-fixer
    - travis_retry composer --no-interaction install --classmap-authoritative
    script:
    - composer --no-interaction run-script test

  - name: Test with PHP 5.4
    dist: trusty
    php: '5.4'
    before_script:
    - phpenv config-rm xdebug.ini || true
    - composer --no-interaction remove --dev --no-update friendsofphp/php-cs-fixer
    - travis_retry composer --no-interaction install --classmap-authoritative
    script:
    - composer --no-interaction run-script test

  - name: Test with PHP 5.5
    dist: trusty
    php: '5.5'
    before_script:
    - phpenv config-rm xdebug.ini || true
    - composer --no-interaction remove --dev --no-update friendsofphp/php-cs-fixer
    - travis_retry composer --no-interaction install --classmap-authoritative
    script:
    - composer --no-interaction run-script test

  - name: Test with PHP 5.6
    php: '5.6'
    before_script:
    - phpenv config-rm xdebug.ini || true
    - composer --no-interaction remove --dev --no-update friendsofphp/php-cs-fixer
    - travis_retry composer --no-interaction install --classmap-authoritative
    script:
    - composer --no-interaction run-script test

  - name: Test with PHP 7.0
    php: '7.0'
    before_script:
    - phpenv config-rm xdebug.ini || true
    - composer --no-interaction remove --dev --no-update friendsofphp/php-cs-fixer
    - travis_retry composer --no-interaction install --classmap-authoritative
    script:
    - composer --no-interaction run-script test

  - name: Test with PHP 7.1
    php: '7.1'
    before_script:
    - phpenv config-rm xdebug.ini || true
    - composer --no-interaction remove --dev --no-update friendsofphp/php-cs-fixer
    - travis_retry composer --no-interaction install --classmap-authoritative
    script:
    - composer --no-interaction run-script test

  - name: Test with PHP 7.2
    php: '7.2'
    before_script:
    - phpenv config-rm xdebug.ini || true
    - composer --no-interaction remove --dev --no-update friendsofphp/php-cs-fixer
    - travis_retry composer --no-interaction install --classmap-authoritative
    script:
    - composer --no-interaction run-script test

  - name: Test with PHP 7.3
    php: '7.3'
    before_script:
    - phpenv config-rm xdebug.ini || true
    - composer --no-interaction remove --dev --no-update friendsofphp/php-cs-fixer
    - travis_retry composer --no-interaction install --classmap-authoritative
    script:
    - composer --no-interaction run-script test

  - name: Test with PHP 7.4
    php: '7.4snapshot'
    before_script:
    - phpenv config-rm xdebug.ini || true
    - composer --no-interaction remove --dev --no-update friendsofphp/php-cs-fixer
    - travis_retry composer --no-interaction install --classmap-authoritative
    script:
    - composer --no-interaction run-script test

  - name: Test with PHP Nightly
    php: nightly
    before_script:
    - phpenv config-rm xdebug.ini || true
    - composer --no-interaction config platform.php 7.4.0
    - composer --no-interaction remove --dev --no-update friendsofphp/php-cs-fixer
    - travis_retry composer --no-interaction install --classmap-authoritative
    script:
    - composer --no-interaction run-script test
